# @package _global_

defaults:
  - _self_
  - datamodule: setfit.yaml
  - model: setfit_nn.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"
batch_size: 8

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
